apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: asp7ys9re-go 
  janus-idp.io/tekton: asp7ys9re-go
  backstage.io/kubernetes-id: asp7ys9re-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: asp7ys9re-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml