apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: asp7ys9re-go
  janus-idp.io/tekton: asp7ys9re-go
  backstage.io/kubernetes-id: asp7ys9re-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: asp7ys9re-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
