apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: asp7ys9re-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: asp7ys9re-go 
  name: asp7ys9re-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: asp7ys9re-go 
